.github/workflows/workflow.yml
src/main/webapp/WEB-INF/appengine-web.xml
src/main/webapp/index.html

Created a directory structure for the web-app that copies the structure used for the personal portfolio. I also added the suggested linter as an action in a .yml file.

Creating directory structure of web app

---

pom.xml
src/main/java/com/google/sps/data/Player.java
src/main/java/com/google/sps/data/SiteUser.java

Included getters and setters for all attributes including email, displayName, imageID, and currentPageID.

Created user object to be used as an entity type. 

---

src/main/webapp/index.html
src/main/webapp/style.css

added a small description paragraph to index.html stating our purpose for designing this webapp

add small description paragraph to index.html

---

src/main/webapp/careerquiz.html
src/main/webapp/careerquiz.js

See here: http://cs-career-step-2020.appspot.com/careerquiz.html

Front end basic design of question and answer

---

src/main/java/com/google/sps/servlets/CareerQuizServlet.java
src/main/webapp/careerquiz.html
src/main/webapp/careerquiz.js
src/main/webapp/choosebranch.html
src/main/webapp/choosebranch.js
src/test/java/com/google/sps/CareerQuizTest.java

Only a few questions have been added and there is no front-end design, but test out the functionality here: http://cs-career-step-2020.appspot.com/careerquiz.html
Selecting choices and clicking submit should lead to another html page that prints out the recommended career choice as a string.

Recommended career branch is found from quiz choices and outputted on new html page

---

.github/workflows/javalinter.yml
src/main/java/com/google/sps/data/CareerQuestionAndChoices.java
src/main/java/com/google/sps/data/CareerQuestionChoice.java
src/main/java/com/google/sps/data/CareerQuestionDatabase.java
src/main/java/com/google/sps/data/GameStage.java
src/main/java/com/google/sps/data/Player.java
src/main/java/com/google/sps/data/ProcessCareerQuizResults.java
src/main/java/com/google/sps/data/RandomEvent.java
src/main/java/com/google/sps/servlets/CareerQuizServlet.java
src/main/java/com/google/sps/servlets/UserAuthServlet.java
src/test/java/com/google/sps/CareerQuizTest.java
src/test/java/com/google/sps/RecommendedCareerPathTest.java

* Create javalinter.yml
* Fixing java synatx with addition of new linter

Create javalinter.yml (#55)

---

src/main/java/com/google/sps/data/ProcessPromotionQuizResults.java
src/test/java/com/google/sps/PromotionQuizResultsTest.java

Class to handle results of Promotion Quiz and unit tests

 Class to handle results of Promotion Quiz and unit tests

---

src/main/java/com/google/sps/servlets/CareerQuizServlet.java
src/main/webapp/promotionquiz.html
src/main/webapp/quiz.js

quiz.js now accepts the servlet name, submit button name, and redirect page as parameters. These three variables distinguish between the career quiz and promotion quiz.

Refactoring so that  the comments quiz and parameters quiz have a shared JS with parameters

---

src/main/java/com/google/sps/data/PromotionMessage.java
src/main/java/com/google/sps/servlets/PromotionQuizServlet.java
src/main/webapp/promotionquiz.html
src/main/webapp/promotionresults.html
src/test/java/com/google/sps/PromotionQuizTest.java

Eventually, this promotion servlet will query the current user for their gameStageId. The GameStage entity will have a QuizKey, which will then take the place of the HARDCODED_QUIZ_KEY to be passed into the QuestionDatabase.

Creating a promotion servlet which displays a hardcoded promotion quiz

---

src/main/java/com/google/sps/servlets/StoreQuestion.java
src/main/webapp/admin/AddStaticData.html
src/test/java/com/google/sps/StoreQuestionTest.java

Next, a similar form will be added for the promotion quiz data and game stage data. Also considering adding a feature to bulk upload data.
For some reason the google-cla bot had a bit of a weird infinite loop and created a bunch of comments but it stopped after I requested a review. If this happens again I will investigate with the technical support engineers.

Creating a servlet to handle inputting in static career quiz servlet data

---

src/main/java/com/google/sps/data/GameStage.java
src/main/java/com/google/sps/data/GameStageDatabase.java
src/test/java/com/google/sps/GameStageDatabaseTest.java

In my next PR, this functionality is used with the admin only form page to allow admins to enter in new game stages.

Creating a GameStage database as an interface for putting and querying game stages (#101)

---

src/main/java/com/google/sps/servlets/StoreGameStage.java
src/main/webapp/admin/AddStaticData.html
src/test/java/com/google/sps/StoreGameStageTest.java

Creating an admin only form to enter in game stage data. Most of the input is checked for validity by the html form.
See the functionality here: http://cs-career-step-2020.appspot.com/admin/AddStaticData.html
(must be logged into google accounts)

Creating an admin only form to enter in game stage data (#103)

---

src/main/java/com/google/sps/servlets/InitializeGameStage.java
src/test/java/com/google/sps/InitializeGameStageTest.java

Sets the users initial game stage to the first level of whatever career path they clicked on.

Servlet that changes users game stage after they click on initial branch

---

src/main/java/com/google/sps/servlets/CareerQuizServlet.java
src/main/java/com/google/sps/servlets/ImageHandlerServlet.java
src/main/webapp/careerquiz.html
src/main/webapp/chooseBranchAdditionalStyling.css
src/main/webapp/choosebranch.html
src/main/webapp/choosebranch.js
src/main/webapp/promotionquiz.html
src/main/webapp/quiz.js

Now, the character design page redirects to the career quiz. After submitting the career quiz, the player is redirected to a page with buttons that allow the character to choose their initial career path, with the recommended career path highlighted. 
The next PR will include the servlet + test (InitializeGameStage) that handles the initialization of the user's game stage from their selection on the choosebranch.html page.

Career quiz now redirects to choose path page with buttons to select different career paths

---

src/main/java/com/google/sps/servlets/GetGameDialogue.java
src/test/java/com/google/sps/GetGameDialogueTest.java

add GetGameDialogue to update the gameStage.html page's dialogue using the PlayersDatabase (implemented in this commit : 77a502d) to access the Players currentPageID which will decide the level you play and the career path the player will follow. Additionaly using the GameStageDatabase (implemented in this commit : 3421029) to get the dialogue belonging to the currentPageID and display it to gameStage.html
add GetGameDialogueTest

Make MVP UIs

---

src/main/webapp/careerquiz.html
src/main/webapp/characterDesign.html
src/main/webapp/quiz.js
src/main/webapp/style.css

Fixing formatting on quiz page

Format Quiz Page and add 8-bit text to quiz page and character design page

---

src/main/java/com/google/sps/servlets/IsFinalStage.java
src/main/webapp/CompletedPath.html
src/main/webapp/gameDialogue.js
src/test/java/com/google/sps/IsFinalStageTest.java

* The IsFinalStage servlet returns "true" if the game stage is the final stage in the career path, and "false" otherwise.
* A test has been added for the servlet.
* The gameDialogue.js file is modified to change the "TRY FOR PROMOTION" button to read "COMPLETE PATH", which redirects to a new html page. In a future PR, this page will be modified to add a button to try another career path.

If the game stage is the final stage in the path, the promotion button is changed to a complete path button

---

src/main/java/com/google/sps/servlets/IsFinalStage.java
src/main/webapp/CompletedPath.html
src/main/webapp/gameDialogue.js
src/test/java/com/google/sps/IsFinalStageTest.java

* The IsFinalStage servlet returns "true" if the game stage is the final stage in the career path, and "false" otherwise.
* A test has been added for the servlet.
* The gameDialogue.js file is modified to change the "TRY FOR PROMOTION" button to read "COMPLETE PATH", which redirects to a new html page. In a future PR, this page will be modified to add a button to try another career path.

If the game stage is the final stage in the path, the promotion button is changed to a complete path button (#143)

---

src/main/webapp/characterDesign.html
src/main/webapp/promotionresults.html
src/main/webapp/style.css

add css to characterDesign.html

add CSS to MVP content

---

src/main/java/com/google/sps/servlets/DeleteUserServlet.java
src/main/webapp/userAuthPage.html
src/main/webapp/userAuthScript.js
src/test/java/com/google/sps/DeleteUserServletTest.java

Fix login page so if already logged in, user has options to 1) return to last stage 2) new game 3) logout.
The new game button uses new Delete-User servlet to clear previous player associated with that email.

Fix login page for users already logged in.

---

src/main/webapp/characterDesign.html
src/main/webapp/characterDesign.js

Every time an image is uploaded to a form, a preview avatar updates.
Check out behavior by uploading files here: http://cs-career-step-2020.appspot.com/characterDesign.html

Character design page now shows character preview as soon as image is uploaded

---

src/main/webapp/gameDialogue.js
src/main/webapp/gameStage.html
src/main/webapp/style.css

add lofi background music to gameStage 
Disclaimer: the music can start automatically this can be changed, for now I made sure the player could play and pause the music based on their own preference to see the live implementation here: https://cs-career-step-2020.wm.r.appspot.com/
next PR play button will be replaced with icons

add background music to gameStage.html

---

src/main/java/com/google/sps/data/PlayerDatabase.java
src/main/java/com/google/sps/servlets/ExperienceServlet.java
src/test/java/com/google/sps/ExperienceServletTest.java

Will fill in the doGet and doPost next.

Create tests for Experience servlet

---

src/main/java/com/google/sps/data/Accessory.java
src/main/java/com/google/sps/data/AccessoryDatabase.java
src/test/java/com/google/sps/AccessoryDatabaseTest.java

Added accessory class to be used for accessory data storage. Image files will be stored in a folder in images. The positioning will be relevant to the image container box.

Creating an AccessoryDatabase to store information about player accessories

---

src/main/java/com/google/sps/data/Meme.java
src/main/java/com/google/sps/data/MemeDatabase.java
src/test/java/com/google/sps/MemeDatabaseTest.java

Next Steps: Create admin webpage to create meme objects

Create Meme and MemeDatabase objects

---

src/main/webapp/gameDialogue.js
src/main/webapp/gameStage.html

exp display has been fixed and is now displayed on the live server, originally there was a problem displaying the experience parameter because the players in the database where not comparable with the the new experience parameter so they where deleted from the database and replaces with new and updated ones

fix display exp in gameStage.html

---

src/main/java/com/google/sps/data/Player.java
src/main/java/com/google/sps/data/PlayerDatabase.java
src/main/java/com/google/sps/servlets/ImageHandlerServlet.java
src/main/java/com/google/sps/servlets/PromotionThresholdServlet.java
src/test/java/com/google/sps/PlayerDatabaseTest.java
src/test/java/com/google/sps/PromotionThresholdServletTest.java

Next Steps: Handle in gameStage.js

Create PromotionThreshold property of player, make servlet to fetch and update it.

---

src/main/java/com/google/sps/data/PlayerDatabase.java
src/main/java/com/google/sps/servlets/ImageHandlerServlet.java
src/main/webapp/gameDialogue.js
src/main/webapp/style.css

Bug: there was a typo where sometimes, the property was called experience, and other times experiencePoints.
The way that threshold changes will be done next with a new servlet that takes the game stage level.

Implement threshold in front end, fix experience bug

---

src/main/java/com/google/sps/servlets/GetPlayerAccessories.java
src/test/java/com/google/sps/GetPlayerAccessoriesTest.java

This serlvet responds with a JSON message containing all accessories that the player has access to, either by default or by earning them throughout the game. 
In the front end, this list will be parsed through to display a menu option where the player can view their available accessories and equip them as desired.

Adding a servlet to fetch all of the player's available/earned accessories

---

src/main/webapp/gameHelper.js

previously gameHelper did not include the functions edited in this PR: https://github.com/googleinterns/step144-2020/pull/184 and now they do

fix add changeThreshold function to gameHelper.js

---

src/main/java/com/google/sps/servlets/StoreAccessory.java
src/main/webapp/admin/StoreAccessory.html
src/main/webapp/admin/storeAccessory.js
src/test/java/com/google/sps/StoreAccessoryTest.java

In this PR, I include a servlet to load in accessories to the database from the form. I also included a message that pops up if the filepath you entered is not a valid image source. All input validity checks are done in the front end form.

Creating servlet and test to store accessories entered in front end form (#192)

---

src/main/webapp/completedPath.html
src/main/webapp/completedPath.js
src/main/webapp/gameHelper.js

add functions deconstructsSentence(), reconstructsSentence(words) to display players nicknames in game while still using AddStaticData.html to query in data

Include player nicknames in dialogue

---

src/main/java/com/google/sps/data/AccessoryDatabase.java
src/main/java/com/google/sps/data/PlayerDatabase.java
src/main/java/com/google/sps/servlets/EarnRandomAccessory.java
src/test/java/com/google/sps/EarnRandomAccessoryTest.java

The get method returns a JSON string representation of a random accessory that is in the accessory database that the player does not already have access to.

Player can now earn a random accessory that they did not already own

---

src/main/java/com/google/sps/servlets/GetEquippedAccessories.java
src/test/java/com/google/sps/GetEquippedAccessoriesTest.java

This doPost method allows Leah's front-end profile page (to be added in the next PR) to set the player's equipped accessories.

Allow front end functionality that sets player's equipped accessories by adding doPost method

---

src/main/java/com/google/sps/servlets/GetGameDialogue.java
src/main/webapp/characterDesign.js
src/main/webapp/gameHelper.js
src/main/webapp/profilePage.html
src/main/webapp/profilePage.js
src/main/webapp/style.css

The Image handling functions in gameHelper.js are not new, just refactored from characterDesign.js

Create Profile Page
